-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 16:24:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vbxqsvvqad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vbxqsvvqad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vbxqsvvqad` DEFAULT CHARACTER SET utf8 ;
USE `vbxqsvvqad` ;

-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`admin` (
  `adminid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`adminid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`staff` (
  `staffid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`staffid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`rider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`rider` (
  `riderid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `contactnumber` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`riderid`),
  UNIQUE INDEX `rider_username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `rider_contactnumber_UNIQUE` (`contactnumber` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`category` (
  `categoryid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`categoryid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`productreadymade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`productreadymade` (
  `productreadymadeid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `imagefilename` TEXT NULL,
  PRIMARY KEY (`productreadymadeid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`productcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`productcategory` (
  `productcategoryid` INT NOT NULL AUTO_INCREMENT,
  `productreadymadeid` INT NOT NULL,
  `categoryid` INT NOT NULL,
  PRIMARY KEY (`productcategoryid`),
  INDEX `fk_productcategory_readymadeproduct_idx` (`productreadymadeid` ASC) VISIBLE,
  INDEX `fk_productcategory_category_idx` (`categoryid` ASC) VISIBLE,
  CONSTRAINT `fk_productcategory_readymadeproduct`
    FOREIGN KEY (`productreadymadeid`)
    REFERENCES `vbxqsvvqad`.`productreadymade` (`productreadymadeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productcategory_category`
    FOREIGN KEY (`categoryid`)
    REFERENCES `vbxqsvvqad`.`category` (`categoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`customer` (
  `customerid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `contactnumber` VARCHAR(13) NOT NULL,
  `address` TEXT NOT NULL,
  `username` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`customerid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`cartproductreadymade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`cartproductreadymade` (
  `cartproductreadymadeid` INT NOT NULL AUTO_INCREMENT,
  `productreadymadeid` INT NOT NULL,
  `customerid` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`cartproductreadymadeid`),
  INDEX `fk_cartproductreadymade_customer_idx` (`customerid` ASC) VISIBLE,
  INDEX `fk_cartproductreadymade_productreadymade_idx` (`productreadymadeid` ASC) VISIBLE,
  CONSTRAINT `fk_cartproductreadymade_customer`
    FOREIGN KEY (`customerid`)
    REFERENCES `vbxqsvvqad`.`customer` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartproductreadymade_productreadymade`
    FOREIGN KEY (`productreadymadeid`)
    REFERENCES `vbxqsvvqad`.`productreadymade` (`productreadymadeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`flavor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`flavor` (
  `flavorid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `imagefilename` TEXT NULL,
  PRIMARY KEY (`flavorid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`shape`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`shape` (
  `shapeid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `imagefilename` TEXT NULL,
  PRIMARY KEY (`shapeid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`size` (
  `sizeid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `imagefilename` TEXT NULL,
  PRIMARY KEY (`sizeid`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`cartproductcustomized`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`cartproductcustomized` (
  `cartproductcustomizedid` INT NOT NULL AUTO_INCREMENT,
  `customerid` INT NOT NULL,
  `flavorid` INT NOT NULL,
  `shapeid` INT NOT NULL,
  `sizeid` INT NOT NULL,
  `quantity` INT NOT NULL,
  `additionalnote` TEXT NULL,
  PRIMARY KEY (`cartproductcustomizedid`),
  INDEX `fk_cartproductcustomized_flavor_idx` (`flavorid` ASC) VISIBLE,
  INDEX `fk_cartproductcustomized_shape_idx` (`shapeid` ASC) VISIBLE,
  INDEX `fk_cartproductcustomized_size_idx` (`sizeid` ASC) VISIBLE,
  INDEX `fk_cartproductcustomized_customer_idx` (`customerid` ASC) VISIBLE,
  CONSTRAINT `fk_cartproductcustomized_flavor`
    FOREIGN KEY (`flavorid`)
    REFERENCES `vbxqsvvqad`.`flavor` (`flavorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartproductcustomized_shape`
    FOREIGN KEY (`shapeid`)
    REFERENCES `vbxqsvvqad`.`shape` (`shapeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartproductcustomized_size`
    FOREIGN KEY (`sizeid`)
    REFERENCES `vbxqsvvqad`.`size` (`sizeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cartproductcustomized_customer`
    FOREIGN KEY (`customerid`)
    REFERENCES `vbxqsvvqad`.`customer` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`order` (
  `orderid` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `customerid` INT NOT NULL,
  `customer` VARCHAR(150) NOT NULL,
  `contactnumber` VARCHAR(13) NOT NULL,
  `datetimeneeded` DATETIME NULL,
  `additionalnote` TEXT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(50) NULL DEFAULT 'Waiting For Confirmation',
  `deliveryoption` VARCHAR(50) NOT NULL,
  `address` TEXT NULL,
  `datetimeonqueue` DATETIME NULL,
  `datetimedeliveredpickedup` DATETIME NULL,
  `imagefilename` TEXT NULL,
  PRIMARY KEY (`orderid`),
  INDEX `fk_order_customer_idx` (`customerid` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer`
    FOREIGN KEY (`customerid`)
    REFERENCES `vbxqsvvqad`.`customer` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`orderhistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`orderhistory` (
  `orderhistoryid` INT NOT NULL AUTO_INCREMENT,
  `datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `orderid` INT NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `person` INT NOT NULL,
  `role` VARCHAR(50) NOT NULL,
  `additionalnote` TEXT NULL,
  PRIMARY KEY (`orderhistoryid`),
  INDEX `fk_orderhistory_order_idx` (`orderid` ASC) VISIBLE,
  CONSTRAINT `fk_orderhistory_order`
    FOREIGN KEY (`orderid`)
    REFERENCES `vbxqsvvqad`.`order` (`orderid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`orderdetailreadymade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`orderdetailreadymade` (
  `orderdetailreadymadeid` INT NOT NULL AUTO_INCREMENT,
  `orderid` INT NOT NULL,
  `productreadymadeid` INT NOT NULL,
  `priceatorder` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL,
  `subtotal` DECIMAL(10,2) GENERATED ALWAYS AS (priceatorder*quantity) VIRTUAL,
  PRIMARY KEY (`orderdetailreadymadeid`),
  INDEX `fk_orderdetailreadymade_order_idx` (`orderid` ASC) VISIBLE,
  INDEX `fk_orderdetailreadymade_productreadymade_idx` (`productreadymadeid` ASC) VISIBLE,
  CONSTRAINT `fk_orderdetailreadymade_order`
    FOREIGN KEY (`orderid`)
    REFERENCES `vbxqsvvqad`.`order` (`orderid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetailreadymade_productreadymade`
    FOREIGN KEY (`productreadymadeid`)
    REFERENCES `vbxqsvvqad`.`productreadymade` (`productreadymadeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`orderdetailcustomized`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`orderdetailcustomized` (
  `orderdetailcustomizedid` INT NOT NULL AUTO_INCREMENT,
  `orderid` INT NOT NULL,
  `flavorid` INT NOT NULL,
  `priceatorderflavor` DECIMAL(10,2) NOT NULL,
  `shapeid` INT NOT NULL,
  `priceatordershape` DECIMAL(10,2) NOT NULL,
  `sizeid` INT NOT NULL,
  `priceatordersize` DECIMAL(10,2) NOT NULL,
  `quantity` INT NOT NULL,
  `subtotal` DECIMAL(10,2) GENERATED ALWAYS AS ((priceatorderflavor+priceatordershape+priceatordersize)*quantity) VIRTUAL,
  `additionalnote` TEXT NULL,
  PRIMARY KEY (`orderdetailcustomizedid`),
  INDEX `fk_orderdetailcustomized_order_idx` (`orderid` ASC) VISIBLE,
  INDEX `fk_orderdetailcustomized_flavor_idx` (`flavorid` ASC) VISIBLE,
  INDEX `fk_orderdetailcustomized_shape_idx` (`shapeid` ASC) VISIBLE,
  INDEX `fk_orderdetailcustomized_size_idx` (`sizeid` ASC) VISIBLE,
  CONSTRAINT `fk_orderdetailcustomized_order`
    FOREIGN KEY (`orderid`)
    REFERENCES `vbxqsvvqad`.`order` (`orderid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetailcustomized_flavor`
    FOREIGN KEY (`flavorid`)
    REFERENCES `vbxqsvvqad`.`flavor` (`flavorid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetailcustomized_shape`
    FOREIGN KEY (`shapeid`)
    REFERENCES `vbxqsvvqad`.`shape` (`shapeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderdetailcustomized_size`
    FOREIGN KEY (`sizeid`)
    REFERENCES `vbxqsvvqad`.`size` (`sizeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vbxqsvvqad`.`orderpayment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vbxqsvvqad`.`orderpayment` (
  `orderpaymentid` INT NOT NULL AUTO_INCREMENT,
  `orderid` INT NOT NULL,
  `datetime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `method` VARCHAR(50) NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `additionalnote` TEXT NULL,
  `iscancelled` CHAR(1) NULL DEFAULT 'n',
  PRIMARY KEY (`orderpaymentid`),
  INDEX `fk_orderpayment_order_idx` (`orderid` ASC) VISIBLE,
  CONSTRAINT `fk_orderpayment_order`
    FOREIGN KEY (`orderid`)
    REFERENCES `vbxqsvvqad`.`order` (`orderid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
